### ISSUE TITLE
Wind-Datei

### ISSUE THREAD

**Issue by natasnat** [DavidWei10/FOSSGIS-Projekt#3]
die Wind-Datei fehlt. Evtl. habt ihr stattdessen aversehentlich das DEM zur Verfügung gestellt?

**Comment by DavidWei10** [comment]
Vielen Dank für den Hinweis, die Winddateien sind nun auch im Ordner zu finden. Das DEM haben wir ausdrücklich als Möglichkeit zum Vergleich für euch hinzugefügt.
